version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teladoc_development
  back:
    build: .
    command: rails s -b '0.0.0.0'
    volumes:
      - ./.:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:

